Analysis for the PML assignment.
========================================================

Analysis for the PML project.

```{r}
library(caret)
set.seed(199)
trainData <- read.csv("data/pml-training.csv")
testData <- read.csv("data/pml-testing.csv")
trainIdx <-createDataPartition(y=trainData$classe, p=0.75, list=FALSE)
trainSet <- trainData[trainIdx, ]
testSet <- trainData[-trainIdx, ]
```


Construct names of all variables of interest:
```{r}
ryp_components <-expand.grid(c("roll","yaw","pitch"), c("dumbbell","arm", "forearm", "belt"))
ryp_predictors <- paste(ryp_components[[1]], ryp_components[[2]], sep="_")
all_predictors <-ryp_predictors
```

Create formula to predict 'classe' based on all predictors:
```{r}
fmla <- as.formula(paste("classe ~ ", paste(all_predictors, collapse= "+")))
print(fmla)
```

Train a random forest model
```{r}
trControl <- trainControl(verboseIter=TRUE, method="none") 
rfModel <- train(
               fmla,
               data = trainSet,
               method="rf",
               importance=TRUE, ntrees=200,
               trControl = trControl,
               tuneGrid = data.frame(mtry=5),
               tuneLength=1)
```

You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
varImpPlot(rfModel$finalModel)
```

Calculate out of sample accuracy (on the test set):
```{r}
predicted <- predict(rfModel, newdata = testSet)
print(confusionMatrix(predicted, testSet$classe))
```



